FROM atlassian/jira-software:latest


#Reverse proxy config
ENV ATL_PROXY_NAME= THE HOSTNAME USED TO ACCESS JIRA THROUGH A WEB BROWSER

ENV ATL_PROXY_PORT= THE PORT USED TO ACCESS JIRA THROUGH A WEB BROWSER



#Databse config
COPY mysql-connector-java-5.1.48.jar /opt/atlassian/jira/lib/mysql-connector-java-5.1.48.jar
